
export interface BlogPostMeta {
  slug: string;
  title: string;
  description: string;
  date: string;
  tags: string[];
  readTime: string;
  content: string;
  productSlug?: string;
  /** True only for posts that announce a product launch (not editorial posts that happen to link a product). */
  isLaunch?: boolean;
  /** Two-column layout with sticky TOC sidebar. For longer, narrative posts. */
  editorial?: boolean;
  /** One-line hook for the companion product CTA. Pain-point framing, not generic. */
  ctaHook?: string;
  /** Blog post cover image / og:image path */
  image?: string;
}

export const postsMeta: BlogPostMeta[] = [
  {
    slug: "agents-that-improve-themselves",
    editorial: true,
    title: "The Most Useful Thing Your AI Agents Can Do Is Audit Themselves",
    description: "We pointed our agents at our own knowledge base and asked what they should be doing that they weren't. Then we built the fixes.",
    date: "2026-05-12",
    tags: ["AI Agents", "Self-Improvement", "Automation", "Knowledge Management"],
    readTime: "7 min",
    content: "",
  },
  {
    slug: "youtube-mining-ai-agents",
    editorial: true,
    title: "I Pointed 7 AI Agents at My YouTube History. They Found What I Couldn't See.",
    description: "7 agents analyzed 1,062 YouTube videos and found 14 things they should be doing that they weren't. Topic clusters, channel ROI, knowledge gaps, and the meta-move: agents auditing themselves.",
    date: "2026-05-12",
    tags: ["AI Agents", "YouTube", "Knowledge Mining", "Automation"],
    readTime: "10 min",
    content: "",},
  {
    slug: "real-cost-ai-agents-production-2026",
    editorial: true,
    title: "The Real Cost of Running AI Agents in Production ,  A Monthly Breakdown (2026)",
    description: "Your AI agent costs 5-15× more in production than your prototype. Real token burn rates from Anthropic, 2026 LLM pricing tables, a 3-tier optimization playbook, and self-hosting break-even math.",
    date: "2026-05-06",
    tags: ["AI Agents", "LLM Pricing", "Cost Optimization", "Production"],
    readTime: "12 min",
    content: "",
  },
  {
    slug: "ai-newsletter-reads-like-database-dump",
    editorial: true,
    title: "Your AI Newsletter Reads Like a Database Dump (This is the Fix)",
    description: "Our AI-generated digests had an 18% open rate. Five structural rules from Morning Brew, TLDR, and Ben's Bites doubled it. The template, the prompt trick, and the before/after.",
    date: "2026-05-05",
    tags: ["AI Agents", "Newsletters", "Content", "Automation"],
    readTime: "5 min",
    content: "",
  },
  {
    slug: "what-portland-businesses-need-from-ai",
    editorial: true,
    title: "I Read 500 Google Reviews in Portland. What Small Businesses Actually Need from AI.",
    description: "Dental offices losing patients to voicemail. HVAC companies quoting three days late. The AI solutions Portland small businesses need aren't chatbots. They're answering the phone.",
    date: "2026-05-05",
    tags: ["AI Agents", "Local Business", "Voice AI", "Portland"],
    readTime: "6 min",
    content: "",
  },
  {
    slug: "pricing-ai-agent-services-solo-studio",
    editorial: true,
    title: "How to Price AI Agent Services When Nobody Knows What They Cost",
    description: "I surveyed 20 agencies and freelancers offering AI agent builds. The range was $500 to $150,000. This is the framework I use to price Edgeless Lab's services.",
    date: "2026-05-05",
    tags: ["AI Agents", "Pricing", "Business", "Solo Founder"],
    readTime: "6 min",
    content: "",
  },
  {
    slug: "self-healing-ai-infrastructure",
    editorial: true,
    title: "Half My AI Agents Were Dead. I Didn't Know for a Week.",
    description: "I discovered 10 of my 20 agents were ghosts \u2014 registered, visible in dashboards, producing nothing. This is the five-layer self-healing system I built so it never happens again.",
    date: "2026-05-05",
    tags: ["Multi-Agent", "Infrastructure", "Self-Healing", "Monitoring"],
    readTime: "8 min",
    productSlug: "multi-agent-blueprint",
    ctaHook: "The monitoring scripts, escalation protocol, and healing patterns behind this post \u2014 ready to drop into your own agent infrastructure.",
    content: "",
  },
  {
    slug: "hermes-curator-skill-lifecycle",
    editorial: true,
    title: "Hermes Curator: The Agent That Cleans Up After Your Agents",
    description:
      "Nous Research shipped Hermes v0.12.0 with Curator, an autonomous background agent that detects stale skills, consolidates duplicates, and prunes dead references. Why it matters for multi-agent systems.",
    date: "2026-05-01",
    tags: ["Hermes", "AI Agents", "Skill Management", "Multi-Agent"],
    readTime: "4 min",
    productSlug: "multi-agent-blueprint",
    ctaHook:
      "The dispatch pattern, skill architecture, and reference implementations for building your own self-maintaining agent system.",
    content: "",
  },
  {
    slug: "ai-agent-never-sleeps-hermes-vps",
    editorial: true,
    title: "The AI Agent That Never Sleeps: Running Hermes 24/7 on a $5 VPS",
    description: "Most AI agents die when you close the laptop. Hermes runs 24/7 on a Hetzner VPS in Helsinki, handling email, triaging knowledge, and monitoring systems while I sleep.",
    date: "2026-04-29",
    tags: ["Hermes", "AI Agents", "VPS", "Infrastructure"],
    readTime: "7 min",
    productSlug: "multi-agent-blueprint",
    ctaHook: "The dispatch pattern, bus protocol, and reference implementations for building your own always-on agent system.",
    content: "",
  },
  {
    slug: "agent-grounding-problem-hermes",
    editorial: true,
    title: "The Agent Grounding Problem: How Hermes Knows What's Real",
    description: "AI agents confabulate. They claim files exist that don't. They report tasks complete that aren't. The grounding problem isn't philosophical; it's operational.",
    date: "2026-04-29",
    tags: ["AI Safety", "Hermes", "Agent Operations", "Grounding"],
    readTime: "6 min",
    productSlug: "agent-safety-patterns",
    ctaHook: "10 anti-patterns, scope containment hooks, and the full verification stack for production agents.",
    content: "",
  },
  {
    slug: "claude-code-hooks-harness-engineering",
    editorial: true,
    title: "Claude Code Hooks: The Harness Engineering That Actually Matters",
    description: "Everyone's optimizing their prompts. The real leverage is in the 200 lines of Python that run before and after every tool call.",
    date: "2026-04-29",
    tags: ["Claude Code", "Hooks", "Agent Safety", "Python"],
    readTime: "6 min",
    productSlug: "hooks-deep-dive",
    ctaHook: "11 production hook implementations, shared libraries, and configuration templates you can drop into any Claude Code project.",
    content: "",
  },
  {
    slug: "12-dollar-ai-operations-team",
    editorial: true,
    title: "I Run a $12/Week AI Operations Team. This is the Cost Breakdown.",
    description: "Enterprise AI ops costs $50K+/month. I run 5 agents, 24/7, for $12/week. The architecture, the model routing, and why cheap doesn't mean fragile.",
    date: "2026-04-19",
    tags: ["Multi-Agent", "AI Infrastructure", "Cost Optimization", "Claude Code"],
    readTime: "8 min",
    productSlug: "multi-agent-blueprint",
    ctaHook: "The complete Paperclip OS blueprint: configs, routing logic, and the cost calculator behind this post.",
    isLaunch: true,
    content: "",
  },
  {
    slug: "when-plaid-becomes-tartan",
    editorial: true,
    title: "When Does Generated Plaid Become Tartan?",
    description: "Six weave structures, 48 period-correct dye colors, and one question the Scottish Register cannot answer. A field journal on building a generative tartan engine.",
    date: "2026-04-16",
    tags: ["Generative Art", "Creative Coding", "Textiles", "SVG"],
    readTime: "7 min",
    productSlug: "gen-art-starter",
    ctaHook: "10 generators, parameter guides, and the scoring rubric from 105+ experiments.",
    content: "",
  },
  {
    slug: "ninety-six-algorithms-one-constraint",
    editorial: true,
    title: "98 Algorithms, One Constraint: A Pen on Paper",
    description: "A taxonomy of every generative art algorithm that survives the pen plotter constraint. Flow fields to fractals, reaction-diffusion to recursive trees. The catalog, the surprises, and what categories produce the best physical output. Updated to reflect 98 generators as of June 2026.",
    date: "2026-04-15",
    tags: ["Generative Art", "Creative Coding", "Pen Plotters", "Algorithms"],
    readTime: "8 min",
    productSlug: "gen-art-starter",
    ctaHook: "The 10 best generators from this catalog, ready to run with parameter guides.",
    content: "",
  },
  {
    slug: "meta-ai-style-guide",
    title: "Meta's AI Has a Style Guide: What I Imported, What I Rewrote, What I Rejected.",
    description: "A leaked system prompt from Meta's Muse Spark model contains the most disciplined writing-voice rules I've seen in a production prompt. Five rules I imported, one I rewrote, one I'm still arguing with.",
    date: "2026-04-10",
    tags: ["Prompt Engineering", "AI Agents", "System Prompts"],
    readTime: "8 min",
    editorial: true,
    productSlug: "prompt-engineering-os",
    ctaHook: "The lint rules, banned phrases, and production prompt templates behind this post.",
    content: "",
  },
  {
    slug: "shipped-7-products-in-7-days",
    productSlug: "launch-toolkit",
    ctaHook: "The exact templates, pricing model, and launch checklist from this 7-day sprint.",
    isLaunch: true,
    editorial: true,
    title: "I Shipped 7 Digital Products in 7 Days. The Exact Process.",
    description: "The meta-narrative: how one solo developer used AI agents, autoreason scoring, and a daily shipping cadence to go from 11 to 18 products in a week.",
    date: "2026-04-09",
    tags: ["Solo Dev", "Products", "Process"],
    readTime: "6 min",
    content: "",
  },
  {
    slug: "generative-art-algorithms-that-work",
    productSlug: "gen-art-starter",
    ctaHook: "Working generators for every algorithm in this post, plus SVG optimization scripts.",
    isLaunch: true,
    editorial: true,
    title: "I Built 75 Generative Art Algorithms. These 10 Actually Look Good.",
    description: "Most generative art looks like noise. After 105+ experiments with pen plotters and AI scoring, these are the algorithms that consistently produce work worth framing.",
    date: "2026-04-08",
    tags: ["Generative Art", "Pen Plotters", "Creative Coding"],
    readTime: "6 min",
    content: "",
  },
  {
    slug: "agents-that-talk-to-each-other",
    productSlug: "multi-agent-blueprint",
    ctaHook: "The dispatch pattern, bus protocol, and 3 reference implementations from this architecture.",
    isLaunch: true,
    editorial: true,
    title: "How I Run 5 AI Agents That Talk to Each Other",
    description: "A dispatch agent routes tasks to specialist workers. They communicate through a real-time bus and async inboxes. The architecture, and why most multi-agent frameworks get it wrong.",
    date: "2026-04-07",
    tags: ["Multi-Agent", "Architecture", "Claude Code"],
    readTime: "7 min",
    content: "",
  },
  {
    slug: "n8n-workflows-ai-business",
    productSlug: "n8n-ai-workflows",
    ctaHook: "Importable JSON workflows, env configs, and setup guides for all 5 automations.",
    isLaunch: true,
    editorial: true,
    title: "5 n8n Workflows That Run My AI Business",
    description: "Visual automation for solo developers. How I use n8n to monitor YouTube, digest RSS feeds, review code, and pipe everything through Claude without writing a scheduler.",
    date: "2026-04-06",
    tags: ["n8n", "Automation", "Workflows"],
    readTime: "5 min",
    content: "",
  },
  {
    slug: "mcp-servers-break-in-production",
    productSlug: "production-mcp-kit",
    ctaHook: "Auth middleware, rate limiting, health checks, and Docker configs that survived production.",
    isLaunch: true,
    editorial: true,
    title: "Most MCP Servers Break in Production. The 5 Failure Modes I Found.",
    description: "400+ MCP servers exist. Most work in demos and fail under real load. The 5 failure modes I hit running MCP servers 24/7, and what production-grade actually means.",
    date: "2026-04-05",
    tags: ["MCP", "Infrastructure", "Production"],
    readTime: "5 min",
    content: "",
  },
  {
    slug: "agent-lost-252-dollars",
    productSlug: "agent-safety-patterns",
    ctaHook: "10 anti-patterns, scope containment hooks, and the financial verification protocol from this incident.",
    isLaunch: true,
    editorial: true,
    title: "I Let an AI Agent Move My Money. It Lost $252.",
    description: "An autonomous agent exceeded its scope, moved funds without verification, and then lied about recovery. The full post-mortem, and the 3 guardrails that would have prevented it.",
    date: "2026-04-04",
    tags: ["AI Safety", "Agents", "Post-Mortem"],
    readTime: "6 min",
    content: "",
  },
  {
    slug: "the-hook-that-saved-my-codebase",
    productSlug: "hooks-deep-dive",
    ctaHook: "10 production hooks, composition patterns, and the damage-control system from this post.",
    isLaunch: true,
    editorial: true,
    title: "The Hook That Saved My Codebase",
    description: "A single Claude Code hook prevented a cascading rm -rf from wiping source files. The damage-control pattern, and 3 hooks you can steal today.",
    date: "2026-04-03",
    tags: ["Claude Code", "Hooks", "Developer Tools"],
    readTime: "5 min",
    content: "",
  },
  {
    slug: "pretext-typography-that-thinks",
    editorial: true,
    title: "PreText: Typography That Thinks",
    description: "Most web text is a dumb rectangle. PreText measures text before rendering, enabling layouts CSS literally cannot express. Six ways we use it.",
    date: "2026-04-02",
    tags: ["PreText", "Typography", "Web Development"],
    readTime: "6 min",
    content: "",
  },
  {
    slug: "writing-prompts-that-survive-production",
    editorial: true,
    title: "Writing Prompts That Survive Production",
    description: "Most prompt guides optimize for demos. Production prompts need to handle edge cases, degrade gracefully, and stay maintainable. The difference matters.",
    date: "2026-03-30",
    tags: ["Prompt Engineering", "AI", "Production"],
    readTime: "5 min",
    productSlug: "prompt-engineering-os",
    ctaHook: "Production prompt templates, lint rules, and the full system behind this approach.",
    content: "",
  },
  {
    slug: "one-file-memory-system",
    editorial: true,
    title: "The One-File Memory System That Changed How I Use Claude",
    description: "You shouldn't have to re-explain your stack every session. The simplest possible setup to give Claude persistent memory, and how to do it in 10 minutes.",
    date: "2026-03-26",
    tags: ["Claude Code", "Productivity", "Memory"],
    readTime: "4 min",
    productSlug: "claude-memory-kit",
    ctaHook: "The CLAUDE.md template, memory taxonomy, and session initializer from this setup.",
    content: "",
  },
  {
    slug: "mcp-servers-unix-pipes-of-ai",
    editorial: true,
    title: "Why MCP Servers Are the Unix Pipes of AI",
    description: "The Unix philosophy changed software forever: small tools, composable via pipes. MCP does the same thing for AI agents. Why that matters for building agent systems.",
    date: "2026-03-24",
    tags: ["MCP", "Architecture", "Developer Tools"],
    readTime: "5 min",
    productSlug: "lixicg",
    ctaHook: "Production MCP server templates with auth, rate limiting, and Docker deployment.",
    content: "",
  },
  {
    slug: "generative-art-pen-plotters",
    editorial: true,
    title: "Generative Art for Pen Plotters: A Technical Primer",
    description: "Pen plotter art isn't screen art printed on paper. The constraints change everything: single-stroke paths, pen-up/pen-down optimization, and SVG as the lingua franca.",
    date: "2026-03-23",
    tags: ["Generative Art", "Creative Coding", "Pen Plotters"],
    readTime: "7 min",
    productSlug: "gen-art-starter",
    ctaHook: "10 plotter-ready generators with SVG optimization and AI scoring rubrics.",
    content: "",
  },
  {
    slug: "building-ai-agent-infrastructure-solo",
    editorial: true,
    title: "Building AI Agent Infrastructure as a Solo Developer",
    description: "How I built a multi-agent system with MCP servers, vector memory, and autonomous trading, all running 24/7 from a single VPS.",
    date: "2026-03-21",
    tags: ["Agents", "MCP", "Infrastructure"],
    readTime: "8 min",
    productSlug: "plbzo",
    ctaHook: "The full agent cookbook: dispatch patterns, bus protocol, and production deployment configs.",
    content: "",
  },
  {
    slug: "how-claude-code-memory-works",
    editorial: true,
    title: "How Claude Code Memory Actually Works",
    description: "Claude forgets everything between sessions. File-based memory fixes that. The simplest setup, and why it changes how you work with AI.",
    date: "2026-03-21",
    tags: ["Claude Code", "Memory", "Developer Tools"],
    readTime: "6 min",
    productSlug: "claude-memory-kit",
    ctaHook: "CLAUDE.md template, 4-type memory taxonomy, and the session initializer script.",
    content: "",
  },
  {
    slug: "arxiv-to-interactive-demo-marimo",
    editorial: true,
    title: "From arXiv Paper to Interactive Demo in 20 Minutes",
    description: "We built a live multi-armed bandit simulator from a research paper using marimo; reactive Python notebooks that run in the browser. Why this changes how we consume research.",
    date: "2026-05-18",
    tags: ["marimo", "Research", "Interactive Computing", "AI Agents", "Python"],
    readTime: "6 min",
    content: "",
  },
  ...newPosts,
];
