export interface CreativeDemo {
  slug: string;
  title: string;
  description: string;
  tags: string[];
  date: string;
  hasControls: boolean;
}

export const creativeDemos: CreativeDemo[] = [
  {
    slug: "tartan-weave-synth",
    title: "Tartan Weave Synth",
    description: "Interactive generative tartan based on Tartanism field notes. 6 weave structures, 48 historical dye colors, mouse-warped threads, and beat-driven color shifts.",
    tags: ["p5.js", "Tartanism", "Interactive", "Weave"],
    date: "2026-06-10",
    hasControls: true,
  },
  {
    slug: "serial-permutation-canvas",
    title: "Serial Permutation Canvas",
    description: "Visualizing total serialism as particle geometry. 12-tone series, prime/retrograde/inversion/rotation permutations, and color-mapped particles.",
    tags: ["p5.js", "Total Serialism", "Algorithmic", "Particles"],
    date: "2026-06-10",
    hasControls: true,
  },
  {
    slug: "scroll-chromatic-excavation",
    title: "Scroll-Chromatic Excavation",
    description: "Scroll through the void to excavate hidden text. Microscopic agents swarm toward dark pixels, revealing buried glyphs. Rebels erase. Builders reveal. Full control panel with sliders.",
    tags: ["p5.js", "Interactive", "Generative Text"],
    date: "2026-06-10",
    hasControls: true,
  },
  {
    slug: "scroll-isometric-dissolution",
    title: "Scroll-Isometric Dissolution",
    description: "Isometric typography dissolves into particles as you scroll. A 3D word space that collapses under velocity.",
    tags: ["p5.js", "Typography", "Scroll"],
    date: "2026-05-28",
    hasControls: false,
  },
  {
    slug: "percussive-archaeology",
    title: "Percussive Archaeology",
    description: "Rhythm-driven excavation of buried text. Each beat spawns agents that dig toward the hidden manuscript.",
    tags: ["p5.js", "Audio", "Generative Text"],
    date: "2026-05-28",
    hasControls: false,
  },
  {
    slug: "cursor-swarm-brush",
    title: "Noise-Shared Cursor Swarm Brush",
    description: "64 particles lerp-track your cursor through a recursive geometric subdivision landscape. Noise-driven turbulence stains tiles as you move.",
    tags: ["Canvas 2D", "Noise", "Particles"],
    date: "2026-05-20",
    hasControls: false,
  },
  {
    slug: "algorithmic-fluid-plotter",
    title: "Algorithmic Fluid Plotter",
    description: "Generative fluid dynamics rendered as pen-plotter compatible vector paths. Perlin noise drives the flow field.",
    tags: ["SVG", "Generative", "Plotter"],
    date: "2026-05-15",
    hasControls: false,
  },
  {
    slug: "kinetic-type-physics",
    title: "Kinetic Type Physics",
    description: "Physics-driven typography where letters have mass, velocity, and collision. Mouse repulsion and gravity well.",
    tags: ["p5.js", "Physics", "Typography"],
    date: "2026-05-12",
    hasControls: false,
  },
  {
    slug: "monolith-drummer",
    title: "Monolith Drummer",
    description: "A 3D monolith that responds to rhythm. Web Audio API drives the geometry, each beat deforms the surface.",
    tags: ["WebGL", "Audio", "3D"],
    date: "2026-05-10",
    hasControls: false,
  },
  {
    slug: "liquid-decryption",
    title: "Liquid Decryption",
    description: "Text emerges from liquid simulation. Each letter is a fluid body that decrypts into position.",
    tags: ["p5.js", "Fluid", "Typography"],
    date: "2026-05-08",
    hasControls: false,
  },
  {
    slug: "elastic-shader-type",
    title: "Elastic Shader Type",
    description: "GLSL shader-driven typography that warps and stretches elastically. Mouse interaction creates ripples through the letterforms.",
    tags: ["WebGL", "GLSL", "Typography"],
    date: "2026-05-05",
    hasControls: false,
  },
  {
    slug: "flow-field-scramble-typography",
    title: "Flow-Field Scramble Typography",
    description: "Letters navigate a vector flow field, scrambling and reassembling into words. Particle-driven text.",
    tags: ["p5.js", "Flow Field", "Typography"],
    date: "2026-05-01",
    hasControls: false,
  },
  {
    slug: "harmonic-particle-atmosphere",
    title: "Harmonic Particle Atmosphere",
    description: "Particles orbit in harmonic resonance, creating emergent patterns from simple rules.",
    tags: ["p5.js", "Particles", "Harmonics"],
    date: "2026-04-28",
    hasControls: false,
  },
  {
    slug: "invisible-wind",
    title: "Invisible Wind",
    description: "Wind forces act on invisible structures. You see only the effect: bending grass, scattering leaves, rippling fabric.",
    tags: ["p5.js", "Physics", "Nature"],
    date: "2026-04-25",
    hasControls: false,
  },
  {
    slug: "glassmorphism-data-atlas",
    title: "Glassmorphism Data Atlas",
    description: "A data visualization dashboard with frosted glass panels, real-time chart updates, and depth-based layering.",
    tags: ["CSS", "Data Viz", "UI"],
    date: "2026-04-20",
    hasControls: false,
  },
  {
    slug: "bespoke-emotion-ledger",
    title: "Bespoke Emotion Ledger",
    description: "Five characters play Prisoner's Dilemma. Each has a distinct strategy, emotional state, and trust score. Visual encoding cycles every round.",
    tags: ["p5.js", "Game Theory", "Data Viz"],
    date: "2026-04-15",
    hasControls: false,
  },
  {
    slug: "demo-chromatic-physics-desk",
    title: "Chromatic Physics Desk",
    description: "Webcam color sampling becomes draggable physics stickers. Difference-blend cursor inverts everything it touches.",
    tags: ["Webcam", "Physics", "CSS"],
    date: "2026-04-10",
    hasControls: false,
  },
  {
    slug: "demo-dot-matrix-cylinder-scroll",
    title: "Dot-Matrix Cylinder Scroll",
    description: "CSS 3D scroll-driven cylinder with 12 living dot-grid canvases. One grid is a live camera feed rendered as 16x16 brightness dots.",
    tags: ["CSS 3D", "Canvas", "Scroll"],
    date: "2026-04-05",
    hasControls: false,
  },
  {
    slug: "elastic-feedback-stage",
    title: "Elastic Feedback Stage",
    description: "An interactive stage where every element has elastic feedback. Click, drag, and release to see the physics.",
    tags: ["p5.js", "Physics", "Interactive"],
    date: "2026-04-01",
    hasControls: false,
  },
  {
    slug: "fluid-font-gauntlet",
    title: "Fluid Font Gauntlet",
    description: "Typography that flows like liquid through a gauntlet of obstacles. Letters split, merge, and reform.",
    tags: ["p5.js", "Fluid", "Typography"],
    date: "2026-03-28",
    hasControls: false,
  },
  {
    slug: "ink-trails-typewriter",
    title: "Ink Trails Typewriter",
    description: "A typewriter where each keystroke leaves an ink trail that bleeds and fades. The text accumulates as a living document.",
    tags: ["p5.js", "Typography", "Ink"],
    date: "2026-03-25",
    hasControls: false,
  },
  {
    slug: "line-monument-valley",
    title: "Line Monument Valley",
    description: "Generative landscapes inspired by Monument Valley. Lines form impossible architecture in isometric space.",
    tags: ["p5.js", "Isometric", "Generative"],
    date: "2026-03-20",
    hasControls: false,
  },
  {
    slug: "paper-atmosphere",
    title: "Paper Atmosphere",
    description: "Atmospheric effects rendered on paper texture. Fog, rain, and light filter through a tactile surface.",
    tags: ["p5.js", "Atmosphere", "Texture"],
    date: "2026-03-15",
    hasControls: false,
  },
  {
    slug: "pen-plotter-decryption",
    title: "Pen-Plotter Decryption",
    description: "A message decrypts itself as a pen plotter draws. Each letter appears as the pen traces its path.",
    tags: ["SVG", "Plotter", "Typography"],
    date: "2026-03-10",
    hasControls: false,
  },
  {
    slug: "phonetic-flow-field",
    title: "Phonetic Flow Field",
    description: "Phonetic symbols navigate a vector field. Each sound has a distinct path and behavior.",
    tags: ["p5.js", "Flow Field", "Phonetics"],
    date: "2026-03-05",
    hasControls: false,
  },
  {
    slug: "postcard-matrix",
    title: "Postcard Matrix",
    description: "A matrix of living postcards, each with its own animation. Click to flip and reveal the back.",
    tags: ["p5.js", "Interactive", "Grid"],
    date: "2026-03-01",
    hasControls: false,
  },
  {
    slug: "sashiko-wave-weaver",
    title: "Sashiko Wave Weaver",
    description: "Sashiko stitching patterns weave into waves. Traditional Japanese craft meets generative motion.",
    tags: ["p5.js", "Sashiko", "Waves"],
    date: "2026-02-25",
    hasControls: false,
  },
  {
    slug: "sashiko-weather",
    title: "Sashiko Weather",
    description: "Weather data visualized through Sashiko stitching patterns. Rain, sun, and wind become thread.",
    tags: ["p5.js", "Sashiko", "Weather"],
    date: "2026-02-20",
    hasControls: false,
  },
  {
    slug: "scroll-particle-swarm",
    title: "Scroll Particle Swarm",
    description: "Scrolling drives a particle swarm. Velocity spawns agents that explore the content.",
    tags: ["p5.js", "Particles", "Scroll"],
    date: "2026-02-15",
    hasControls: false,
  },
  {
    slug: "segregation-engine",
    title: "Segregation Engine",
    description: "Schelling's segregation model as an interactive engine. Adjustable tolerance and density.",
    tags: ["p5.js", "Simulation", "Agent-Based"],
    date: "2026-02-10",
    hasControls: true,
  },
  {
    slug: "sticky-magnetic-blueprint",
    title: "Sticky Magnetic Blueprint",
    description: "Magnetic sticky notes on a blueprint grid. Drag, snap, and organize your ideas.",
    tags: ["p5.js", "Interactive", "UI"],
    date: "2026-02-05",
    hasControls: false,
  },
  {
    slug: "synesthetic-weather-typewriter",
    title: "Synesthetic Weather Typewriter",
    description: "Each keystroke produces weather. Type a storm, a sunny day, or a foggy morning.",
    tags: ["p5.js", "Synesthesia", "Weather"],
    date: "2026-02-01",
    hasControls: false,
  },
  {
    slug: "tessellated-breath",
    title: "Tessellated Breath",
    description: "Breathing tessellation patterns that expand and contract. Each cell responds to its neighbors.",
    tags: ["p5.js", "Tessellation", "Breathing"],
    date: "2026-01-28",
    hasControls: false,
  },
  {
    slug: "tessellated-swarm-letterform",
    title: "Tessellated Swarm Letterform",
    description: "Letterforms built from tessellated swarms. Each letter is a colony of agents.",
    tags: ["p5.js", "Tessellation", "Swarm"],
    date: "2026-01-25",
    hasControls: false,
  },
  {
    slug: "volumetric-liquid-glyph",
    title: "Volumetric Liquid Glyph",
    description: "3D liquid glyphs rendered with volumetric shading. Each letter is a fluid body in space.",
    tags: ["p5.js", "3D", "Liquid"],
    date: "2026-01-20",
    hasControls: false,
  },
  {
    slug: "corrupted-manuscript",
    title: "Corrupted Manuscript",
    description: "A manuscript that corrupts itself as you read. Text degrades, glitches, and reforms.",
    tags: ["p5.js", "Glitch", "Text"],
    date: "2026-01-15",
    hasControls: false,
  },
  {
    slug: "flow-field-typography",
    title: "Flow-Field Typography",
    description: "Typography that flows through a vector field. Letters navigate obstacles and follow paths.",
    tags: ["p5.js", "Flow Field", "Typography"],
    date: "2026-01-10",
    hasControls: false,
  },
  {
    slug: "demo-ghost-sashiko-weaver",
    title: "Ghost Sashiko Weaver",
    description: "Sashiko patterns woven by ghost agents. Invisible hands stitch traditional patterns.",
    tags: ["p5.js", "Sashiko", "Agents"],
    date: "2026-01-05",
    hasControls: false,
  },
];
