export const projects = [
  {
    slug: "pamela",
    title: "Pamela",
    description: "Autonomous prediction market agent. ML-driven position sizing, live on Polymarket 24/7.",
    longDescription: "Pamela is an autonomous trading agent that monitors prediction markets on Polymarket, identifies mispriced contracts using ML-driven sentiment analysis and probability estimation, and executes trades with intelligent position sizing. Built in TypeScript, deployed on a Hetzner VPS, managed by PM2 for 24/7 uptime.",
    tags: ["TypeScript", "ML", "Polymarket", "PM2"],
    category: "Agents",
    snippet: `$ pm2 status pamela\n│ online │ 0 restarts\n\n24/7 autonomous execution`,
    stack: ["TypeScript", "Node.js", "PM2", "Hetzner VPS", "Polymarket API"],
    status: "Live",
  },
  {
    slug: "mcp-servers",
    title: "MCP Servers",
    description: "Production servers for ChromaDB, knowledge search, and multi-agent orchestration.",
    longDescription: "A suite of Model Context Protocol servers that give AI agents access to structured knowledge. Includes ChromaDB vector search, Obsidian vault querying, semantic memory retrieval, and multi-agent task dispatch. Built with Effect-TS for type-safe, composable server definitions.",
    tags: ["MCP", "Effect-TS", "ChromaDB", "TypeScript"],
    category: "Infrastructure",
    snippet: `server.tool("search", {\n  query: z.string(),\n  collection: z.enum([\n    "vault", "memory"\n  ])\n})`,
    stack: ["TypeScript", "Effect-TS", "ChromaDB", "Zod", "MCP SDK"],
    status: "Live",
  },
  {
    slug: "pen-plotter-art",
    title: "Pen Plotter Art",
    description: "Generative art experiments scored by an AI judge. SVG to physical media pipeline.",
    longDescription: "A generative art pipeline that produces SVG artwork optimized for pen plotters. Experiments exploring strange attractors, Hilbert curves, Voronoi tessellations, and flow fields. Each piece is scored by an AI judge on composition, line quality, and visual interest. The best pieces get plotted on an AxiDraw with archival ink on cotton paper.",
    tags: ["Generative Art", "Python", "SVG", "AxiDraw"],
    category: "Creative",
    snippet: `<svg viewBox="0 0 400 400">\n  <path d="M200,50 C350,100\n    350,300 200,350" />\n</svg>`,
    stack: ["Python", "SVG", "AxiDraw", "Pillow", "NumPy"],
    status: "Active",
  },
  {
    slug: "mastra-orchestrator",
    title: "Mastra Orchestrator",
    description: "Multi-agent routing and task dispatch across Claude, Gemini, and local models.",
    longDescription: "A Mastra-based orchestration layer that routes tasks to the best-fit AI model. Claude Opus handles deep reasoning, Gemini Flash handles search and fast queries, and local models handle drafting. Includes a 10-tool API for reading/writing backlog items, searching the knowledge vault, dispatching tasks to agents, and monitoring VPS services.",
    tags: ["Mastra", "Multi-Agent", "TypeScript"],
    category: "Agents",
    snippet: `router → claude-opus (thinking)\nrouter → gemini-flash (search)\nrouter → local-llama (draft)\n✓ consensus reached`,
    stack: ["TypeScript", "Mastra", "OpenRouter", "PM2"],
    status: "Live",
  },
  {
    slug: "knowledge-api",
    title: "Knowledge API",
    description: "Semantic search across thousands of documents. ChromaDB + Obsidian + vector embeddings.",
    longDescription: "A unified search API that queries across ChromaDB vector embeddings, Obsidian vault markdown files, and PyTorch-generated memory tensors. Supports natural language queries with configurable similarity thresholds and collection filtering. Powers the knowledge retrieval layer for all agents in the system.",
    tags: ["ChromaDB", "Python", "API", "Embeddings"],
    category: "Infrastructure",
    snippet: `qmd search "agent orchestration"\n  --collection claude-vault\n  --top-k 10 --min-score 0.6`,
    stack: ["Python", "ChromaDB", "FastAPI", "Sentence Transformers"],
    status: "Live",
  },
  {
    slug: "llm-client",
    title: "LLM Client",
    description: "Unified client with automatic fallback across OpenRouter, Gemini, Anthropic, and OpenAI.",
    longDescription: "A Python client that abstracts away provider differences and implements intelligent fallback. Tries OpenRouter first (widest model access), falls back to Gemini, then Anthropic, then OpenAI. Handles rate limiting, quota exhaustion, and provider outages transparently. Used by every Python-based tool in the system.",
    tags: ["Python", "OpenRouter", "Multi-Provider"],
    category: "Infrastructure",
    snippet: `client = UnifiedLLM()\nresult = client.complete(\n  "analyze this market",\n  model="auto"  # best available\n)`,
    stack: ["Python", "OpenRouter", "Gemini API", "Anthropic SDK"],
    status: "Live",
  },
];

export const experiments = [
  {
    slug: "strange-attractors",
    title: "Strange Attractors",
    description: "Lorenz, Rossler, and Chen attractor systems rendered as SVG paths for pen plotting. Real-time parameter exploration with live preview.",
    category: "Generative",
    status: "Active",
  },
  {
    slug: "knowledge-graph",
    title: "Knowledge Graph",
    description: "Force-directed visualization of documents across ChromaDB collections, Obsidian vault links, and semantic similarity edges.",
    category: "Data",
    status: "Live",
  },
  {
    slug: "total-serialism",
    title: "Total Serialism",
    description: "Algorithmic music composition using serialist techniques. Generates both audio output and visual score notation from tone rows and transformation matrices.",
    category: "Audio",
    status: "Live",
    href: "https://djmclaudeassistant-web.github.io/total-serialism/",
  },
  {
    slug: "tartanism",
    title: "Tartanism",
    description: "Generative tartan pattern explorer. Procedural plaid generation with historical clan data, color theory, and interactive weaving visualization.",
    category: "Generative",
    status: "Live",
    href: "https://djmclaudeassistant-web.github.io/tartanism/",
  },
  {
    slug: "mastra-orchestrator",
    title: "Mastra Orchestrator",
    description: "Visual dashboard for multi-agent task routing. Real-time display of agent states, message passing, and consensus formation across Claude, Gemini, and local models.",
    category: "Agents",
    status: "Live",
  },
  {
    slug: "pen-plotter-art",
    title: "Pen Plotter Art",
    description: "Generative SVG art pipeline with AI scoring. Dozens of unique generators producing work across flow fields, attractors, tessellations, and algorithmic calligraphy.",
    category: "Generative",
    status: "Active",
  },
  {
    slug: "excalidraw-diagrams",
    title: "Excalidraw Diagrams",
    description: "Auto-generated architecture diagrams using a custom Excalidraw generator. Covering system topology, data flows, and agent interactions.",
    category: "Data",
    status: "Active",
  },
];
