/**
 * AUTO-GENERATED by make_catalog.py — do not edit by hand.
 * Import these in data.ts instead of hardcoding counts.
 */
export const PLOTTER = {
  run:        18,
  factories:  40,
  pieces:     "41,572",
  kept:       "39,414",
  curated:    "1,296",
  best:       "89.1",
  withheld:   "38,118",
} as const;
