/**
 * AUTO-GENERATED by make_catalog.py — do not edit by hand.
 * Import these in data.ts instead of hardcoding counts.
 */
export const PLOTTER = {
  run:        16,
  factories:  20,
  pieces:     "24,973",
  kept:       "24,860",
  curated:    "1,296",
  best:       "89.1",
  withheld:   "23,564",
} as const;
