/*
 * ship-log.ts — Build-time ship log data pipeline for edgelesslab.com homepage.
 *
 * Data sources:
 *   PRSs   → edgeless-ai GitHub PRs merged recently (zero: direct-push workflow)
 *   Paperclip → closed Paperclip issues with workProducts (none: field empty)
 *   Blog   → blog.ts launch posts + recent posts
 *   Locally-published Git commits → parsed locally (primary signal)
 *
 * Output: `public/ship-log.json` — cached static JSON, consumed at build time.
 * Run via:    `tsx scripts/generate-ship-log.ts`
 * Add to package.json scripts:  "generate:ship-log": "tsx scripts/generate-ship-log.ts"
 *
 * Homepage integration:
 *   ShipLog component in home-client.tsx reads from `src/lib/ship-log.data.ts`
 *   (Plain JSON data, re-generated by build script).
 */

/* ------------------------------------------------------------------ */
/* ShipItem type                                                       */

export interface ShipItem {
  id: string;
  kind: "pr" | "paperclip" | "post" | "commit";
  date: string;       // "YYYY-MM-DD"
  title: string;
  href: string;
  meta: string;
  kindLabel: string;  // human-readable label
}

/* ------------------------------------------------------------------ */
/* ShipLogData — holds pre-computed items exported by build script     */

export interface ShipLogData {
  generatedAt: string;
  commitsSince: string;
  items: ShipItem[];
}

/* ------------------------------------------------------------------ */
/* Lazy-load from static JSON                                          */

let _cache: ShipLogData | null = null;
let _pending: Promise<ShipLogData> | null = null;

/**
 * Ship items are baked into `public/ship-log.json` at build time.
 * Fetch once, cache for the session.
 */
export async function getShipLog(): Promise<ShipLogData> {
  if (_cache) return _cache;
  if (!_pending) {
    _pending = fetch("/ship-log.json")
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json() as Promise<ShipLogData>;
      })
      .catch((err) => {
        console.warn("[ship-log] failed to load:", err);
        return {
          generatedAt: new Date().toISOString().slice(0, 10),
          commitsSince: "unknown",
          items: [],
        } satisfies ShipLogData;
      })
      .then((data) => {
        _cache = data;
        _pending = null;
        return data;
      });
  }
  return _pending;
}

/**
 * Synchronous low-risk call — reads from public/header in same origin.
 * Returns empty list if not yet loaded.
 */
export function getShipLogSync(): ShipItem[] {
  return _cache?.items ?? [];
}
