// Generated by scripts/design-system/generate.mjs. Edit the reviewed recipe.
import type { CSSProperties, ReactNode } from "react";
import Link from "next/link";
import tokens from "./tokens.json";
import styles from "./primitives.module.css";

type Children = { children: ReactNode };
export type Measure = keyof typeof tokens.measure;
export type HeadingKind = keyof typeof tokens.heading;
export type TextVariant = keyof typeof tokens.text;
export type Space = keyof typeof tokens.spacing;
export type Elevation = keyof typeof tokens.elevation;
export type LinkTarget = `/${string}` | `mailto:${string}`;
const variables: CSSProperties & Record<`--polar-${string}`, string> = {
  "--polar-color-canvas-dark": tokens.color.canvas.dark,
  "--polar-color-canvas-light": tokens.color.canvas.light,
  "--polar-color-primary-dark": tokens.color.primary.dark,
  "--polar-color-primary-light": tokens.color.primary.light,
  "--polar-color-secondary-dark": tokens.color.secondary.dark,
  "--polar-color-secondary-light": tokens.color.secondary.light,
  "--polar-color-muted-dark": tokens.color.muted.dark,
  "--polar-color-muted-light": tokens.color.muted.light,
  "--polar-color-accent-dark": tokens.color.accent.dark,
  "--polar-color-accent-light": tokens.color.accent.light,
  "--polar-color-accentHover-dark": tokens.color.accentHover.dark,
  "--polar-color-accentHover-light": tokens.color.accentHover.light,
  "--polar-color-shellCanvas-dark": tokens.color.shellCanvas.dark,
  "--polar-color-shellCanvas-light": tokens.color.shellCanvas.light,
  "--polar-color-shellGlass-dark": tokens.color.shellGlass.dark,
  "--polar-color-shellGlass-light": tokens.color.shellGlass.light,
  "--polar-spacing-gutter": tokens.spacing.gutter,
  "--polar-spacing-pageTop": tokens.spacing.pageTop,
  "--polar-spacing-pageBottom": tokens.spacing.pageBottom,
  "--polar-spacing-backLink": tokens.spacing.backLink,
  "--polar-spacing-title": tokens.spacing.title,
  "--polar-spacing-intro": tokens.spacing.intro,
  "--polar-spacing-paragraph": tokens.spacing.paragraph,
  "--polar-spacing-section": tokens.spacing.section,
  "--polar-spacing-heading": tokens.spacing.heading,
  "--polar-spacing-listIndent": tokens.spacing.listIndent,
  "--polar-spacing-listItem": tokens.spacing.listItem,
  "--polar-spacing-focus": tokens.spacing.focus,
  "--polar-measure-page": tokens.measure.page,
  "--polar-measure-reading": tokens.measure.reading,
  "--polar-heading-title-size": tokens.heading.title.size,
  "--polar-heading-title-weight": tokens.heading.title.weight,
  "--polar-heading-title-lineHeight": tokens.heading.title.lineHeight,
  "--polar-heading-title-tracking": tokens.heading.title.tracking,
  "--polar-heading-section-size": tokens.heading.section.size,
  "--polar-heading-section-weight": tokens.heading.section.weight,
  "--polar-heading-section-lineHeight": tokens.heading.section.lineHeight,
  "--polar-heading-section-tracking": tokens.heading.section.tracking,
  "--polar-text-body-size": tokens.text.body.size,
  "--polar-text-body-lineHeight": tokens.text.body.lineHeight,
  "--polar-text-subtitle-size": tokens.text.subtitle.size,
  "--polar-text-subtitle-lineHeight": tokens.text.subtitle.lineHeight,
  "--polar-font-backSize": tokens.font.backSize,
  "--polar-font-backLineHeight": tokens.font.backLineHeight,
  "--polar-font-strongWeight": tokens.font.strongWeight,
  "--polar-elevation-none": tokens.elevation.none,
  "--polar-layout-pageMinimum": tokens.layout.pageMinimum,
  "--polar-layout-zero": tokens.layout.zero,
  "--polar-layout-auto": tokens.layout.auto,
  "--polar-motion-link": tokens.motion.link,
  "--polar-motion-linkEase": tokens.motion.linkEase,
};

export function Surface({ children, elevation = "none" }: Children & { elevation?: Elevation }) {
  return <div className={styles.surface + " " + styles["elevation_" + elevation]} style={variables}>{children}</div>;
}
export function Main({ children }: Children) {
  return <main id="main-content" tabIndex={-1} className={styles.main}>{children}</main>;
}
export function Container({ children, measure }: Children & { measure: Measure }) {
  return <div className={styles["measure_" + measure]}>{children}</div>;
}
export function Heading({ children, kind }: Children & { kind: HeadingKind }) {
  return kind === "title" ? <h1 className={styles.title}>{children}</h1> : <h2 className={styles.sectionHeading}>{children}</h2>;
}
export function Text({ children, variant = "body" }: Children & { variant?: TextVariant }) {
  return <p className={styles["text_" + variant]}>{children}</p>;
}
export function Section({ children, spaceAfter = "section" }: Children & { spaceAfter?: Space }) {
  return <section className={styles["space_" + spaceAfter]}>{children}</section>;
}
export function List({ children }: Children) {
  return <ul className={styles.list}>{children}</ul>;
}
export function ListItem({ children }: Children) {
  return <li className={styles.listItem}>{children}</li>;
}
export function Strong({ children }: Children) {
  return <strong className={styles.strong}>{children}</strong>;
}
export function BackLink({ children, href }: Children & { href: LinkTarget }) {
  return <Link href={href} className={styles.backLink}>{children}</Link>;
}
export function InlineLink({ children, href }: Children & { href: LinkTarget }) {
  return <a href={href} className={styles.inlineLink}>{children}</a>;
}
