/** Reviewed adapter recipe. No consumer code is evaluated here.
 * Raw theme/metric values live exclusively in tokens.json. The generated TSX
 * and CSS are checked structurally; changing this recipe is a policy change.
 */
export const primitiveNames = [
  'Surface', 'Main', 'Container', 'Heading', 'Text', 'Section',
  'List', 'ListItem', 'Strong', 'BackLink', 'InlineLink',
];

export function flattenTokens(value, path = []) {
  return Object.entries(value).flatMap(([key, entry]) =>
    typeof entry === 'string'
      ? [[`--polar-${[...path, key].join('-')}`, [...path, key]]]
      : flattenTokens(entry, [...path, key]));
}

export function adapterSource(catalog) {
  const variables = flattenTokens(catalog).map(([name, path]) =>
    `  "${name}": tokens.${path.join('.')},`).join('\n');
  return `// Generated by scripts/design-system/generate.mjs. Edit the reviewed recipe.
import type { CSSProperties, ReactNode } from "react";
import Link from "next/link";
import tokens from "./tokens.json";
import styles from "./primitives.module.css";

type Children = { children: ReactNode };
export type Measure = keyof typeof tokens.measure;
export type HeadingKind = keyof typeof tokens.heading;
export type TextVariant = keyof typeof tokens.text;
export type Space = keyof typeof tokens.spacing;
export type Elevation = keyof typeof tokens.elevation;
export type LinkTarget = \`/\${string}\` | \`mailto:\${string}\`;
const variables: CSSProperties & Record<\`--polar-\${string}\`, string> = {
${variables}
};

export function Surface({ children, elevation = "none" }: Children & { elevation?: Elevation }) {
  return <div className={styles.surface + " " + styles["elevation_" + elevation]} style={variables}>{children}</div>;
}
export function Main({ children }: Children) {
  return <main id="main-content" tabIndex={-1} className={styles.main}>{children}</main>;
}
export function Container({ children, measure }: Children & { measure: Measure }) {
  return <div className={styles["measure_" + measure]}>{children}</div>;
}
export function Heading({ children, kind }: Children & { kind: HeadingKind }) {
  return kind === "title" ? <h1 className={styles.title}>{children}</h1> : <h2 className={styles.sectionHeading}>{children}</h2>;
}
export function Text({ children, variant = "body" }: Children & { variant?: TextVariant }) {
  return <p className={styles["text_" + variant]}>{children}</p>;
}
export function Section({ children, spaceAfter = "section" }: Children & { spaceAfter?: Space }) {
  return <section className={styles["space_" + spaceAfter]}>{children}</section>;
}
export function List({ children }: Children) {
  return <ul className={styles.list}>{children}</ul>;
}
export function ListItem({ children }: Children) {
  return <li className={styles.listItem}>{children}</li>;
}
export function Strong({ children }: Children) {
  return <strong className={styles.strong}>{children}</strong>;
}
export function BackLink({ children, href }: Children & { href: LinkTarget }) {
  return <Link href={href} className={styles.backLink}>{children}</Link>;
}
export function InlineLink({ children, href }: Children & { href: LinkTarget }) {
  return <a href={href} className={styles.inlineLink}>{children}</a>;
}
`;
}

export function adapterCss(catalog) {
  const v = (name) => `var(--polar-${name})`;
  const colorVars = (theme) => Object.fromEntries(Object.keys(catalog.color).map(key =>
    [`--polar-color-${key}`, v(`color-${key}-${theme}`)]));
  const typeRules = (group, kind) => ({
    'font-size': v(`${group}-${kind}-size`),
    'line-height': v(`${group}-${kind}-lineHeight`),
    ...(group === 'heading' ? {
      'font-weight': v(`${group}-${kind}-weight`),
      'letter-spacing': v(`${group}-${kind}-tracking`),
    } : {}),
  });
  const rules = {
    '.surface': { ...colorVars('dark'), '--bg-glass': v('color-shellGlass'), display: 'flex', 'flex-direction': 'column', 'min-height': v('layout-pageMinimum'), background: v('color-shellCanvas') },
    ':global(html[data-theme="light"]) .surface': colorVars('light'),
    '.main': { background: v('color-canvas'), 'padding-inline': v('spacing-gutter'), 'padding-top': v('spacing-pageTop'), 'padding-bottom': v('spacing-pageBottom'), color: v('color-primary') },
    ...Object.fromEntries(Object.keys(catalog.measure).map(key => [`.measure_${key}`, { 'max-width': v(`measure-${key}`), ...(key === 'page' ? { 'margin-inline': v('layout-auto') } : {}) }])),
    ...Object.fromEntries(Object.keys(catalog.spacing).map(key => [`.space_${key}`, { 'margin-bottom': v(`spacing-${key}`) }])),
    ...Object.fromEntries(Object.keys(catalog.elevation).map(key => [`.elevation_${key}`, { 'box-shadow': v(`elevation-${key}`) }])),
    '.title': { ...typeRules('heading', 'title'), color: v('color-primary'), 'margin-bottom': v('spacing-title') },
    '.sectionHeading': { ...typeRules('heading', 'section'), color: v('color-accent'), 'margin-top': v('spacing-section'), 'margin-bottom': v('spacing-heading') },
    '.text_body': { ...typeRules('text', 'body'), color: v('color-secondary'), 'margin-bottom': v('spacing-paragraph'), 'text-wrap': 'pretty' },
    '.text_subtitle': { ...typeRules('text', 'subtitle'), color: v('color-muted'), 'margin-bottom': v('spacing-intro') },
    '.list': { ...typeRules('text', 'body'), color: v('color-secondary'), 'margin-bottom': v('spacing-paragraph'), 'padding-left': v('spacing-listIndent'), 'list-style-type': 'disc' },
    '.listItem': { 'margin-bottom': v('spacing-listItem') },
    '.strong': { color: v('color-primary'), 'font-weight': v('font-strongWeight') },
    '.backLink': { display: 'inline-block', color: v('color-muted'), 'font-size': v('font-backSize'), 'line-height': v('font-backLineHeight'), 'margin-bottom': v('spacing-backLink'), transition: `color ${v('motion-link')} ${v('motion-linkEase')}` },
    '.inlineLink': { color: v('color-accent'), 'text-decoration': 'underline', 'text-underline-offset': v('spacing-focus'), transition: `color ${v('motion-link')}` },
    '.inlineLink:hover': { color: v('color-accentHover') },
    '.main:focus-visible, .backLink:focus-visible, .inlineLink:focus-visible': { outline: `${v('spacing-focus')} solid ${v('color-accent')}`, 'outline-offset': v('spacing-focus'), 'border-radius': v('spacing-focus') },
  };
  return Object.entries(rules).map(([selector, declarations]) =>
    `${selector} {\n${Object.entries(declarations).map(([name, value]) => `  ${name}: ${value};`).join('\n')}\n}`).join('\n\n') + '\n';
}
