import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Soul Memo | Edgeless Lab",
  description: "Deep essays on the thinkers, builders, and visionaries who shape our world.",
};

interface SoulMemo {
  slug: string;
  soul: string;
  title: string;
  excerpt: string;
  date: string;
  category: string;
}

const soulMemos: SoulMemo[] = [
  {
    slug: "mark-cuban-effort",
    soul: "Mark Cuban",
    title: "The Last Man Who Believes in Hustle",
    excerpt: "In 1999, Mark Cuban sold Broadcast.com for $5.7 billion. He walked away with $1.4 billion. When the dot-com bubble burst, he became one of the few billionaires who kept their billions. But this isn't a story about luck—it's about a man who believes effort is the only variable you control.",
    date: "2026-05-29",
    category: "Business",
  },
  // Future entries will be auto-populated by Verse
];

export default function SoulMemoPage() {
  return (
    <main className="min-h-screen bg-[#f7f7f5]">
      <div className="max-w-3xl mx-auto px-6 py-16">
        {/* Header */}
        <div className="mb-12">
          <div className="flex items-center gap-2 text-sm text-[#888] mb-4">
            <Link href="/blog" className="hover:text-[#111] transition-colors">
              Blog
            </Link>
            <span>/</span>
            <span className="text-[#111]">Soul Memo</span>
          </div>
          <h1 className="text-4xl font-bold text-[#111] mb-4">Soul Memo</h1>
          <p className="text-lg text-[#666] leading-relaxed">
            Deep essays on the thinkers, builders, and visionaries who shape our world.
            Each essay is written by channeling the soul's voice—not describing them, but
            speaking as them.
          </p>
        </div>

        {/* Newsletter CTA */}
        <div className="bg-[#111] text-white rounded-lg p-6 mb-12">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-xl font-semibold mb-2">Subscribe to Soul Memo</h3>
              <p className="text-sm text-[#aaa]">
                One soul, one deep essay, delivered to your inbox weekly.
              </p>
            </div>
            <div className="text-right">
              <div className="text-2xl font-bold">$25<span className="text-sm font-normal">/mo</span></div>
              <button className="mt-2 bg-white text-[#111] px-4 py-2 rounded text-sm font-medium hover:bg-[#f0f0f0] transition-colors">
                Subscribe
              </button>
            </div>
          </div>
        </div>

        {/* Essay List */}
        <div className="space-y-8">
          {soulMemos.map((memo) => (
            <article
              key={memo.slug}
              className="bg-white rounded-lg p-6 border border-[#e0e0e0] hover:border-[#111] transition-colors"
            >
              <div className="flex items-center gap-2 text-sm text-[#888] mb-3">
                <span className="bg-[#f0f0f0] px-2 py-1 rounded">{memo.category}</span>
                <span>{memo.date}</span>
              </div>
              <h2 className="text-2xl font-bold text-[#111] mb-3">
                <Link href={`/blog/soul-memo/${memo.slug}`} className="hover:underline">
                  {memo.title}
                </Link>
              </h2>
              <p className="text-[#666] leading-relaxed mb-4">{memo.excerpt}</p>
              <div className="flex items-center gap-2 text-sm">
                <span className="font-medium text-[#111]">Soul:</span>
                <span className="text-[#666]">{memo.soul}</span>
              </div>
            </article>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-16 pt-8 border-t border-[#e0e0e0]">
          <p className="text-sm text-[#888]">
            Essays are generated by Verse, the Edgeless newsletter agent, using real
            research and primary sources. Every quote is verified. Every claim is sourced.
          </p>
        </div>
      </div>
    </main>
  );
}
