var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/lab/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-9wdxk._.js")
R.c("server/chunks/ssr/01sj_next_dist_esm_build_templates_app-page_048cylt.js")
R.c("server/chunks/ssr/01sj_next_dist_11y0nj.._.js")
R.c("server/chunks/ssr/[root-of-the-server]__07qjis.._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0osr6sc._.js")
R.c("server/chunks/ssr/01sj_0p8ey8a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0foscwx._.js")
R.c("server/chunks/ssr/01sj_next_dist_client_components_0p.330u._.js")
R.c("server/chunks/ssr/01sj_next_dist_client_components_builtin_forbidden_0cnq9s4.js")
R.c("server/chunks/ssr/01sj_next_dist_client_components_builtin_unauthorized_02d7.fh.js")
R.c("server/chunks/ssr/01sj_next_dist_client_components_builtin_global-error_05oj0d~.js")
R.c("server/chunks/ssr/0lwq_edgeless-website__next-internal_server_app_lab_page_actions_0t-gsj-.js")
R.m(34400)
module.exports=R.m(34400).exports
