var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0hsd~mt._.js")
R.c("server/chunks/ssr/01sj_next_dist_esm_build_templates_app-page_0q-dh3-.js")
R.c("server/chunks/ssr/01sj_next_dist_11y0nj.._.js")
R.c("server/chunks/ssr/[root-of-the-server]__07qjis.._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0osr6sc._.js")
R.c("server/chunks/ssr/01sj_0p8ey8a._.js")
R.c("server/chunks/ssr/01sj_next_dist_client_components_builtin_global-error_05oj0d~.js")
R.c("server/chunks/ssr/0lwq_edgeless-website__next-internal_server_app__global-error_page_actions_0aa~o2e.js")
R.m(81522)
module.exports=R.m(81522).exports
