// Golden-parity tests: mix/wrapIndex must match the Python reference
// (blender.py _mix/_wrap_index) EXACTLY; ratio within 1e-12 of Python's
// difflib.SequenceMatcher; stripFlags exact. Fixtures generated by
// generated/nous-mj-overnight/export_dashboard_data.py.

import { describe, expect, it } from "vitest";
import { mix, wrapIndex } from "../coverage";
import { quickRatioBound, ratio, stripFlags } from "../dedupe";
import golden from "./fixtures/golden.json";

interface MixFixture {
  k: number;
  salt: number;
  out: string;
}

interface WrapFixture {
  n: number;
  salt: number;
  seq: number[];
}

interface RatioFixture {
  a: string;
  b: string;
  ratio: string;
}

interface StripFixture {
  raw: string;
  stripped: string;
}

describe("mix golden parity", () => {
  it("matches every Python _mix fixture exactly", () => {
    for (const f of golden.mix as MixFixture[]) {
      expect(mix(BigInt(f.k), BigInt(f.salt)).toString()).toBe(f.out);
    }
  });
});

describe("wrapIndex golden parity", () => {
  it("matches every Python _wrap_index sequence exactly", () => {
    for (const f of golden.wrapIndex as WrapFixture[]) {
      const got = f.seq.map((_v, k) => wrapIndex(k, f.n, f.salt));
      expect(got).toEqual(f.seq);
    }
  });

  it("is a fair permutation within each wrap", () => {
    for (const f of golden.wrapIndex as WrapFixture[]) {
      const wraps = Math.floor(f.seq.length / f.n);
      for (let w = 0; w < wraps; w++) {
        const wrapSlice = f.seq.slice(w * f.n, (w + 1) * f.n);
        expect(new Set(wrapSlice).size).toBe(f.n);
      }
    }
  });
});

describe("ratio golden parity", () => {
  it("is within 1e-12 of Python difflib on every fixture", () => {
    for (const f of golden.ratio as RatioFixture[]) {
      expect(Math.abs(ratio(f.a, f.b) - Number(f.ratio))).toBeLessThan(1e-12);
    }
  });

  it("quickRatioBound is an upper bound on true ratio for every fixture", () => {
    for (const f of golden.ratio as RatioFixture[]) {
      expect(quickRatioBound(f.a, f.b)).toBeGreaterThanOrEqual(ratio(f.a, f.b) - 1e-15);
    }
  });
});

describe("stripFlags golden parity", () => {
  it("matches the Python strip lambda exactly on every fixture", () => {
    for (const f of golden.strip as StripFixture[]) {
      expect(stripFlags(f.raw)).toBe(f.stripped);
    }
  });
});

describe("bank sizes match the Python source", () => {
  it("keeps the exported banks in sync with the fixture snapshot", async () => {
    const { banks } = await import("../banks");
    expect(Object.keys(banks.INFLUENCE)).toHaveLength(golden.bankSizes.influence);
    expect(banks.SUBJECTS).toHaveLength(golden.bankSizes.subjects);
    expect(banks.SUBJECTS_LARGE).toHaveLength(golden.bankSizes.subjectsLarge);
    expect(banks.PALETTE).toHaveLength(golden.bankSizes.palette);
  });
});
